Viagogo/Models/Event.cs
using GogoKit.Models.Response;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Viagogo.Models
{
    public class Event
    {
        public string eventName { get; set; }
        public string minticketprice { get; set; }
        public DateTimeOffset? eventDate { get; set; }
        public int? noofTickets { get; internal set; }
        public int? id { get; set; }
    }
}

Viagogo/Models/FilterModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Viagogo.Models
{
    public class FilterModel
    {
        public List<Viagogo.Models.Event> lst {get; set;}
        public int? noofTickets { get; set; }
        public DateTimeOffset? filterDate { get; set; }
        public DateTimeOffset? filterDateE { get; set; }
    }
}

Viagogo/Models/Searchstring.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Viagogo.Models
{
    public class SearchString
    {
        public string searchStr { get; set; }
    }
}

Viagogo/Models/Ticket.cs
using GogoKit.Models.Response;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Viagogo.Models
{
    public class Ticket
    {
        public Money price { get; set; }
        public TicketType description { get; set; }
        public int noOfTickets { get; set; }
    }
}

Viagogo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GogoKit;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Viagogo.Models;
using GogoKit.Models.Response;

namespace Viagogo.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index(int? id)
        {
            Session["found"] = " ";
            if (id == 1)
            {
                Session["found"] = "No events found for your query :( !";
            }
            return View();
        }
        private string conv(Money money)
        {
            if (money != null)
                return money.Display;
            else
                return "N/A";
        }

        public ActionResult Lookup()
        {
            return RedirectToAction("Index");
        }
        public DateTime transform(DateTimeOffset? date)
        {
            DateTime d = new DateTime(date.Value.Year, date.Value.Month, date.Value.Day, date.Value.Hour, date.Value.Minute, date.Value.Second);
            return d;
        }
        public bool dateisin(DateTimeOffset? ed, DateTimeOffset? ld, DateTimeOffset? eventd)
        {
            if (DateTime.Compare(transform(ed), transform(eventd)) < 0 && DateTime.Compare(transform(eventd), transform(ld)) < 0)
                return true;
            else
                return false;
        }

        [HttpPost]
        public ActionResult Search(FilterModel model)
        {
            List<Models.Event> filteredlist = (List<Models.Event>)Session["Events"]; 
            if(model.noofTickets != null)
            {
                var helper = new List<Models.Event>();
                foreach (var ev in filteredlist)
                {
                    if (ev.noofTickets >= model.noofTickets) 
                       helper.Add(ev);
                }
                filteredlist = helper;
            }
            if (model.filterDate != null && model.filterDateE != null)
            {
                var helper = new List<Models.Event>();
                foreach (var ev in filteredlist)
                {
                    if (dateisin(model.filterDate, model.filterDateE, ev.eventDate))
                        helper.Add(ev);
                }
                filteredlist = helper;
            }
            FilterModel filterobject = new FilterModel();
            filterobject.lst = filteredlist;

            return View("Lookup",filterobject);
        }

        [HttpPost]
        public async Task<ActionResult> Lookup(SearchString search)
        {
            
            search.searchStr = search.searchStr == null ? "EMPTY SEARCH" : search.searchStr;
            if (search.searchStr == "EMPTY SEARCH")
                return RedirectToAction("Index", new { id = 1 });

            var existsEvent = false;
            var client = new ViagogoClient(new ProductHeaderValue("AwesomeApp", "1.0"), "TaRJnBcw1ZvYOXENCtj5",
                           "ixGDUqRA5coOHf3FQysjd704BPptwbk6zZreELW2aCYSmIT8XJ9ngvN1MuKV");
            var token = await client.OAuth2.GetClientAccessTokenAsync(/*List of scopes*/ new string[] { });
            await client.TokenStore.SetTokenAsync(token);
            var searchResults = await client.Search.GetAllAsync(search.searchStr);

            List<Models.Event> eventcollection = new List<Models.Event>();

            foreach (var res in searchResults)
            {
                if (res.Type == "Event")
                {
                    var currEvent = await client.Hypermedia.GetAsync<GogoKit.Models.Response.Event>(res.EventLink);
                    eventcollection.Add(new Models.Event()
                    {
                        eventName = res.Title,
                        minticketprice = conv(currEvent.MinTicketPrice),
                        eventDate = currEvent.StartDate,
                        noofTickets = currEvent.NumberOfTickets,
                        id = currEvent.Id
                    });
                    existsEvent = true;
                }
            }

            Session["events"] = eventcollection;
            if (existsEvent)
            {
                FilterModel filterobject = new FilterModel();
                filterobject.lst = eventcollection;
                return View(filterobject);
            }
            else
                return RedirectToAction("Index", new { id = 1 });
            
        }
    }
}

Viagogo/Controllers/TicketController.cs
using GogoKit;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace Viagogo.Controllers
{
    public class TicketController : Controller
    {
        public ActionResult Index()
        {
            return Content("MAMMA");
        }

        [HttpGet]
        public ActionResult Buy()
        {
            return RedirectToAction("Home","Index");
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> Buy(string id)
        {
            var client = new ViagogoClient(new ProductHeaderValue("AwesomeApp", "1.0"), "TaRJnBcw1ZvYOXENCtj5",
                           "ixGDUqRA5coOHf3FQysjd704BPptwbk6zZreELW2aCYSmIT8XJ9ngvN1MuKV");
            var token = await client.OAuth2.GetClientAccessTokenAsync(/*List of scopes*/ new string[] { });
            await client.TokenStore.SetTokenAsync(token);

            int idasint;
            Int32.TryParse(id, out idasint);
            var listings = await client.Listings.GetAllByEventAsync(idasint);
            var listcollection = new List<Models.Ticket>();

            foreach (var res in listings)
            {
                 listcollection.Add(new Models.Ticket()
                 {
                     price = res.EstimatedTotalTicketPrice,
                     description = res.TicketType,
                     noOfTickets = (int)res.NumberOfTickets
                 });
                 
            }

            return View(listcollection);
        }
    }
}

Viagogo/Views/Home/Index.cshtml
@model Viagogo.Models.SearchString

@{
    ViewBag.Title = "Index";
}

<!DOCTYPE>
<html>
    <body>
        <div>
            <p class="text-danger">
                @Session["found"]
            </p>
            <br>
            Type the name of the artist you would like to see here:
            <br>
            <form action="~/Home/Lookup" method="post">
                @Html.TextBoxFor(m=> Model.searchStr)<br>
                <input type="submit" id="btnSend" value="Send" />
            </form>
        </div>
    </body>
</html>

Viagogo/Views/Home/Lookup.cshtml
@model Viagogo.Models.FilterModel

@{
    ViewBag.Title = "Lookup";
}

<!DOCTYPE>
<html>
<head>
</head>
<body>
    <div class="form-group">
        <br>
                @using (Html.BeginForm("Search", "Home", FormMethod.Post))
                {
                    <label>Tickets:</label>
                    @Html.TextBoxFor(m => m.noofTickets)
                    <label>Start date:</label>
                    @Html.TextBoxFor(m => m.filterDate)
                    <label>End date:</label>
                    @Html.TextBoxFor(m => m.filterDateE)
                    <input type="submit" value="Filter" />
                }
        <br>
        <table style="width:100%">
            <tr>
                <th>EVENT NAME:</th>
                <th>EVENT DATE:</th>
                <th>LOWEST PRICE:</th>
                <th>TICKETS AVIALBLE:</th>
                <th>BUY TICKETS</th>
            </tr>
            @{ 
                foreach (var ev in Model.lst)
                {
                    <tr>
                        <td>@ev.eventName</td>
                        <td>@ev.eventDate</td>
                        <td>@ev.minticketprice</td>
                        <td>@ev.noofTickets</td>
                        <td>@using (Html.BeginForm("Buy", "Ticket", new { id = @ev.id }))
                        {
                            <input type="submit" value="Buy" class="button1">
                        }
                        </td>
                    </tr>
               }
            }
        </table>
    </div>
</body>
</html>

Viagogo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Viagogo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Viagogo/Views/Ticket/Buy.cshtml
@model List<Viagogo.Models.Ticket>

@{
    ViewBag.Title = "Buy";
}

<!DOCTYPE>
<html>
<body>
    <div>
        <table style="width:100%">
            <tr>
                <td>PRICE:</td>
                <td>NO OF TICKETS:</td>
                <td>DESCRIPTION:</td> 
                <td>BUY FROM HERE:</td>            
            </tr>
            @{
                foreach (var list in Model)
                {
                    <tr>
                         <td>@list.price.Display</td>
                         <td>@list.noOfTickets</td>
                         @if (@list.description.Name != @list.description.Type)
                         {<td>@list.description.Type - @list.description.Name</td>}
                         else
                         {<td>@list.description.Type</td>}
                         <td><input type="submit" value="View Tickets here" class="button1" /></td>
                    </tr>
                }
              }
        </table>
    </div>
</body>
</html>